version: '3.5'
services:
  web:
    build:
      context: .
      args:
        - BUILD_ARG=dev
    image: docker-registry.data.amsterdam.nl/ois/blackspots-frontend:${VERSION:-latest}
    environment:
      - TZ=Europe/Amsterdam
    ipc: host
    ports:
      - '3000:80'

  unittest:
    build:
      context: .
      target: builder
    environment:
      - NODE_ENV=test
      - CI=true
      - TZ=Europe/Amsterdam
      - BUILD_ARG=acc
    command: npm run test

  upgrade:
    build:
      context: .
      target: upgrade
    environment:
      - NODE_ENV=development
      - CI=true
      - TZ=Europe/Amsterdam
      - BUILD_ARG=dev
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: ncu -u --doctor --target minor